name: Code Coverage

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  coverage:
    name: Generate & Upload Coverage
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
      - name: Get installed Playwright version
        id: playwright-version
        run: echo -n "{version}={$(npm ls @playwright/test --json | jq --raw-output '.dependencies["@playwright/test"].version')}" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        id: playwright-cache
        with:
          path: '~/.cache/ms-playwright'
          key: '${{ runner.os }}-playwright-${{ steps.playwright-version.outputs.version }}'
          restore-keys: |
            ${{ runner.os }}-playwright-
      - name: Install Playwright's dependencies
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: npx playwright install --with-deps
      - run: npx nx run-many --target=test --all --parallel=3 --coverage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
