name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    name: 'Lint, Test, Build & Deploy'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'
      - uses: nrwl/nx-set-shas@v3
      - name: Setup Git
        run: |
          git config user.name "GitHub Bot"
          git config user.email "gituser@example.com"
      - run: npm ci
      - name: Install Playwright
        run: npx playwright install --with-deps
      - run: npx nx workspace-lint
      - run: npx nx format:check --verbose
      - run: npx nx affected --target=lint --parallel=3
      - run: npx nx affected --target=build --parallel=3
      - run: npx nx affected --target=test --parallel=3 --coverage
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      - name: Version
        if: github.ref == 'refs/heads/main'
        run: npx nx affected --target=version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Tag last-release
        if: github.ref == 'refs/heads/main'
        run: |
          git tag -f last-release
          git push origin last-release --force
